site_name: Whitepapers
site_description: Building Docs on Github with MkDocs
site_author: Christopher Sansone

repo_url: https://github.com/csansone/Whitepapers
repo_name: Whitepapers

theme:
    name: material

docs_dir: docs_raw
site_dir: docs
